name: conventionnal-pr-title
author: Zadkiel <hello@zadkiel.fr>
description: Ensure your PR title matches the Conventional Commits spec (https://www.conventionalcommits.org/).
inputs:
  success-state:
    description: Description of the status check if validation succeeds.
    required: true
    default: Title follows the specification.
  failure-state:
    description: Description of the status check if validation fails.
    required: true
    default: Title does not follow the specification.
  context-name:
    description: Persistent status check context key
    required: true
    default: conventional-pr-title
runs:
  using: node12
  main: src/index.js
branding:
  icon: shield
  color: green
